routes/web.php
<?php

use UniSharp\LaravelFilemanager\Lfm;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/',  function(){
//     return view('index');
// } )->name('/');

Route::get('admin/migration-command', function () {
    
    \Artisan::call('migrate');
    dd("Done");
});


Route::get('/' , 'Frontend\HomeController@index')->name('/');
// Route::get('/' , 'HomeController@index')->name('/');
Route::get('/home' , 'HomeController@showDashbaord' )->name('home');

Route::get('/admin/login' , 'HomeController@login' )->name('dashboard.login');

Route::group( ['prefix'=>'admin','as'=>'admin.' , 'middleware' => ['auth' , 'admin']  ] , function(){


    Route::get('/',  'HomeController@adminDashboard' )->name('index');
    Route::get('/user/{id}/profile' , 'UserController@editProfile')->name('user.profile');
    Route::post('/user/{id}/profile/update' , 'UserController@updateProfile')->name('user.profile.update');
    Route::resource('users', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('subcategory', 'SubCategoryController');
    Route::resource('product', 'ProductController');
    Route::post('product-on-sale/{id}', 'ProductController@product_on_sale')->name('product.on.sale');
    Route::post('product-status/{id}', 'ProductController@change_status')->name('product.status');
    Route::resource('vendors', 'VendorController');
    Route::resource('brands', 'BrandController');
    Route::post('brands-status/{id}', 'BrandController@change_status')->name('brands.status');
    Route::resource('delivery_boys', 'DeliveryBoyController');
    Route::resource('coupens', 'CoupenController');
    Route::resource('newsletters', 'NewsletterController');
    Route::get('media-managment' , function(){
        return view('media.media'); })->name('media-managment');
    Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['auth']], function () {
        Lfm::routes();
    });
} );


    Route::get('/', 'Frontend\HomeController@mainPage' )->name('index');
    Route::get('/about-us', 'HomeController@about_us' )->name('about-us');


    Route::group( ['prefix'=>'dashboard','as'=>'dashboard.' , 'middleware' => 'auth'  ]  , function(){
        Route::get('/' , 'HomeController@customerDashboard' )->name('index');
} );

Route::get('clear' , function(){
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    return 'clear';
} );

Route::get('test', function () {
    return view('test');
    // return view('testing');

});

Auth::routes();


// Route::get('test' , function(){
//     return view('layouts.admin');
// } );



//  admin routes 
Route::resource('admin/categories','Admin\CategoryController');
Route::post('admin/categories-status/{id}','Admin\CategoryController@change_status')->name('categories.status');
Route::resource('admin/subcategory-type','Admin\SubcategoryTypeController');
Route::post('admin/subcategory-typ-status/{id}','Admin\SubcategoryTypeController@change_status')->name('subcategory.typ.status');
Route::resource('admin/subcategories','Admin\SubcategoryController');
Route::post('admin/subcategories-status/{id}','Admin\SubcategoryController@change_status')->name('subcategories.status');

Route::resource('admin/home-slider','Admin\HomeSliderController');
Route::post('admin/home-slider-status/{id}','Admin\HomeSliderController@change_status')->name('home.slider.status');
Route::resource('admin/banner-images','Admin\BannerImagesController');
Route::post('admin/banner-images-status/{id}','Admin\BannerImagesController@change_status')->name('banner.images.status');

Route::resource('admin/products','Admin\ProdcutController');
Route::post('admin/products-status/{id}','Admin\ProdcutController@change_status')->name('products.status');

Route::resource('admin/featured-products','Admin\FeaturedCategoryController');
// featured-subcategory-type routes 
Route::get('admin/featured-subcateory-type/{id}','Admin\FeaturedCategoryController@features_subcatet')->name('featured.subcategory.type');
Route::get('admin/create-featured-subcateory-type/{id}','Admin\FeaturedCategoryController@create_features_subcatet')->name('create.featured.subcategory.type');
Route::post('admin/store-featured-subcateory-type/{id}','Admin\FeaturedCategoryController@store_features_subcatet')->name('store.featured.subcategory.type');
Route::delete('admin/destroy-featured-subcateory-type/{id}','Admin\FeaturedCategoryController@destroy_features_subcatet')->name('destroy.featured.subcategory.type');

// featured-subcategory routes 
Route::get('admin/featured-subcateory/{id}','Admin\FeaturedCategoryController@features_subcategory')->name('featured.subcategory');
Route::get('admin/create-featured-subcateory/{id}','Admin\FeaturedCategoryController@create_features_subcategory')->name('create.featured.subcategory');
Route::post('admin/store-featured-subcateory/{id}','Admin\FeaturedCategoryController@store_features_subcategory')->name('store.featured.subcategory');
Route::delete('admin/destroy-featured-subcateory/{id}','Admin\FeaturedCategoryController@destroy_features_subcategory')->name('destroy.featured.subcategory');

// featured-products routes 
Route::get('admin/featured-product/{id}','Admin\FeaturedCategoryController@features_products')->name('featured.product');
Route::get('admin/create-featured-products/{id}','Admin\FeaturedCategoryController@create_features_products')->name('create.featured.products');
Route::post('admin/store-featured-products/{id}','Admin\FeaturedCategoryController@store_features_products')->name('store.featured.products');
Route::delete('admin/destroy-featured-products/{id}','Admin\FeaturedCategoryController@destroy_features_products')->name('destroy.featured.products');



// new products routes
Route::resource('admin/new-products','Admin\NewProductController');
// featured-subcategory-type routes 
Route::get('admin/new-subcateory-type/{id}','Admin\NewProductController@features_subcatet')->name('new.subcategory.type');
Route::get('admin/create-new-subcateory-type/{id}','Admin\NewProductController@create_features_subcatet')->name('create.new.subcategory.type');
Route::post('admin/store-new-subcateory-type/{id}','Admin\NewProductController@store_features_subcatet')->name('store.new.subcategory.type');
Route::delete('admin/destroy-new-subcateory-type/{id}','Admin\NewProductController@destroy_features_subcatet')->name('destroy.new.subcategory.type');

// featured-subcategory routes 
Route::get('admin/new-subcateory/{id}','Admin\NewProductController@features_subcategory')->name('new.subcategory');
Route::get('admin/create-new-subcateory/{id}','Admin\NewProductController@create_features_subcategory')->name('create.new.subcategory');
Route::post('admin/store-new-subcateory/{id}','Admin\NewProductController@store_features_subcategory')->name('store.new.subcategory');
Route::delete('admin/destroy-new-subcateory/{id}','Admin\NewProductController@destroy_features_subcategory')->name('destroy.new.subcategory');

// featured-products routes 
Route::get('admin/new-product/{id}','Admin\NewProductController@features_products')->name('new.product');
Route::get('admin/create-new-products/{id}','Admin\NewProductController@create_features_products')->name('create.new.products');
Route::post('admin/store-new-products/{id}','Admin\NewProductController@store_features_products')->name('store.new.products');
Route::delete('admin/destroy-new-products/{id}','Admin\NewProductController@destroy_features_products')->name('destroy.new.products');


// hot products route
Route::resource('admin/hot-products','Admin\HotProductController');
// featured-subcategory-type routes 
Route::get('admin/hot-subcateory-type/{id}','Admin\HotProductController@features_subcatet')->name('hot.subcategory.type');
Route::get('admin/create-hot-subcateory-type/{id}','Admin\HotProductController@create_features_subcatet')->name('create.hot.subcategory.type');
Route::post('admin/store-hot-subcateory-type/{id}','Admin\HotProductController@store_features_subcatet')->name('store.hot.subcategory.type');
Route::delete('admin/destroy-hot-subcateory-type/{id}','Admin\HotProductController@destroy_features_subcatet')->name('destroy.hot.subcategory.type');

// featured-subcategory routes 
Route::get('admin/hot-subcateory/{id}','Admin\HotProductController@features_subcategory')->name('hot.subcategory');
Route::get('admin/create-hot-subcateory/{id}','Admin\HotProductController@create_features_subcategory')->name('create.hot.subcategory');
Route::post('admin/store-hot-subcateory/{id}','Admin\HotProductController@store_features_subcategory')->name('store.hot.subcategory');
Route::delete('admin/destroy-hot-subcateory/{id}','Admin\HotProductController@destroy_features_subcategory')->name('destroy.hot.subcategory');

// featured-products routes 
Route::get('admin/hot-product/{id}','Admin\HotProductController@features_products')->name('hot.product');
Route::get('admin/create-hot-products/{id}','Admin\HotProductController@create_features_products')->name('create.hot.products');
Route::post('admin/store-hot-products/{id}','Admin\HotProductController@store_features_products')->name('store.hot.products');
Route::delete('admin/destroy-hot-products/{id}','Admin\HotProductController@destroy_features_products')->name('destroy.hot.products');



Route::post('ajax/listingtab_/{id}','Frontend\HomeController@featured_products');



Route::get('admin/featured-subcateory/{id}','Admin\FeaturedCategoryController@features_subcategory')->name('featured.subcategory');



// Route::resource('admin/new-products','Admin\NewProductsController');
// Route::resource('admin/hot-products','Admin\HotCategoryController');

app/Models/Subcategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Subcategory extends Model
{
    
	protected $table = 'subcategories';
 	protected $primaryKey = 'id';

    protected $guarded = [];
    
    public function subcategory_type(){
    	return $this->belongsTo(SubcategoryType::class,'id');
    }

    public function subcategory_type_name(){
    	return $this->belongsTo(SubcategoryType::class,'id')->select('sct_name');
    }

    public function product(){
    	return $this->hasMany('App\Product','subc_id');
    }
}

app/Models/SubcategoryType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SubcategoryType extends Model
{
    protected $table = 'subcategory_types';
 	protected $primaryKey = 'id';

    protected $guarded = [];
    
    public function category(){
    	return $this->belongsTo(Category::class,'id');
    }

    public function subcategory(){
    	return $this->hasMany(Subcategory::class,'sct_id');
    }

    public function category_name(){
    	return $this->belongsTo(Category::class,'id')->select('c_name');
    }
}

app/SubCategory.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SubCategory extends Model
{
    protected $guarded = [];

    public function parent(){
        return $this->belongsTo('App\Category' , 'category_id');
    }
}

app/Http/Controllers/Admin/SubcategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Subcategory;
use App\Models\SubcategoryType;

class SubcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategory = Subcategory::paginate(20);
        return view('admin.category.subcategory.index',compact('subcategory'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $subcategory_type = SubcategoryType::all();
        return view('admin.category.subcategory.form',compact('subcategory_type'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
           'sc_name' => 'required',
           'sct_id' => 'required',
           'description' => 'sometimes',
        ]);

        
        $subcategory = new Subcategory();

        $subcategory->sct_id = $request->sct_id;
        $subcategory->sc_name = $request->sc_name;
        $subcategory->status = $request->status;
        $subcategory->description = $request->description;

        if ($request->file('image_name')) {
            $file = $request->image_name;
            $folder = 'subcategory';
            $subcategory->image_name = saveImages($file, $folder);
        }
        if ($request->file('sc_icon')) {
            $file = $request->sc_icon;
            $folder = 'subcategory';
            $subcategory->sc_icon = saveIcons($file, $folder);
        }
        $subcategory->save();

        if($subcategory){
            return redirect()->route('subcategories.index')->with('success' , 'Category added successfully');
        }else{
            return redirect()->back()->with('error' , 'Some problem occoured');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subcategory_type = SubcategoryType::all();
        $subcategory = Subcategory::find($id);
         return view('admin.category.subcategory.edit',compact('subcategory_type','subcategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
           'sc_name' => 'required',
           'sct_id' => 'required',
           'description' => 'sometimes',
        ]);

        
        $subcategory = Subcategory::find($id);
        $subcategory->sct_id = $request->sct_id;
        $subcategory->sc_name = $request->sc_name;
        $subcategory->status = $request->status;
        $subcategory->description = $request->description;

        if ($request->file('image_name')) {
            $file = $request->image_name;
            $folder = 'subcategory';
            $old_file_name = $subcategory->image_name;
            $subcategory->image_name = saveImages($file, $folder,$old_file_name);
        }

        if ($request->file('sc_icon')) {
            $file = $request->sc_icon;
            $folder = 'subcategory';
            $old_file_name = $subcategory->sc_icon;
            $subcategory->sc_icon = saveIcons($file, $folder,$old_file_name);
        }

        $subcategory->save();
        
        if($subcategory){
            return redirect()->route('subcategories.index')->with('success' , 'Category updated successfully');
        }else{
            return redirect()->back()->with('error' , 'Some problem occoured');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subcategory = Subcategory::find($id);
        $subcategory->delete();
    }

    public function change_status($id){
    
        $subcategory = Subcategory::find($id);
        $subcategory->status = $subcategory->status == 1 ? 0 : 1;
        $subcategory->save();
        if($subcategory){
            return redirect()->route('subcategories.index')->with('success' , 'Status updated successfully');
        }else{
            return redirect()->back()->with('error' , 'Some problem occoured');
        }
    }

    public function subCategory($id){
        dd("id is = ".$id);
    }
}

resources/views/admin/new-products/subcategory/include/create-form.blade.php
<div class="row">

    @if($errors->any() )
    @foreach ($errors->all() as $error)
        <p class="alert alert-danger"> {{$error}} </p>
    @endforeach
    @endif

    @if(session()->has('success'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: '{{session("success")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('error'))
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '{{session("error")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('message'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'info',
            title: '{{session("message")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
@section('styles')
<link rel="stylesheet" href="{{asset('/admin-plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('/admin-plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">

@endsection

<div class="col-md-12" style="padding:30px" >
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">New Subcategory</h3>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
      <form action="{{route('store.new.subcategory',$id)}}" method="POST" enctype="multipart/form-data">
          @csrf
       <div class="form-group row">
          <div class="col-sm-2">
          <label for="sc_name" class="row float-right col-form-label ">Subcategory:</label>
        </div>
          <div class="col-sm-8">
            <select class="select2bs4" multiple id="e1" name="subcategories[]" data-placeholder="Select Categories" style="width: 100%;">
          @foreach($subcategories as $category)
            <option value="{{$category->id}}"> {{ $category->sc_name }} </option>
          @endforeach
        </select> 
          </div>
        </div>

      <hr>

    
        <div>
            <button class="btn btn-primary float-right">Create</button>
        </div>
      </form>
    </div>
    </div>
  
  </div>
</div>


@section('scripts')

<script src=" {{asset('/admin-plugins/select2/js/select2.full.min.js')}}"></script>
<script>

  $('.select2bs4').select2({
    theme: 'bootstrap4',
  });

  $("#e1").select2();

</script>

@endsection

resources/views/admin/new-products/subcategory/include/table.blade.php
<div class="row">


    @if($errors->any() )
    @foreach ($errors->all() as $error)
        <p class="alert alert-danger"> {{$error}} </p>
    @endforeach
    @endif

    @if(session()->has('success'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: '{{session("success")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('error'))
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '{{session("error")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('message'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'info',
            title: '{{session("message")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif

<div class="col-md-12" style="padding:30px" >
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Categories</h3>
        <a href="{{route('create.new.subcategory',$id)}}" class="btn btn-success float-right" > <i class="fas fa-list"></i> Create Category</a>
      </div> 
      <!-- /.card-header -->
      <div class="card-body">
        <table class="table table-bordered table-hover">
          <thead>                  
            <tr>
              <th>#</th>
              <th>Name</th>
              <th>Subcategory Type</th>
              <th>Icon</th>
              <th>Image</th>
              <th>Description</th>
              <th>Status</th>
              <th>Action</th>
            </tr> 
          </thead>
          <tbody>
              @foreach ($subcategory as $k => $value)
              {{-- @php 
                dd($value);
              @endphp --}}
              @if(!empty($value->subcategory))
            <tr>
               <td>{{$k+1}}.</td>
              <td>{{ $value->subcategory->sc_name }}</td>
              <td> {{ $value->subcategory->subcategory_type_name->sct_name }} </td>
              <td> 
                <img src="{{ asset('/uploads/subcategory/icons'.'/'.$value->subcategory->sc_icon ) }}">
               
              </td>
              <td> 
                <img src="{{ asset('/uploads/subcategory/thumbnails'.'/'.$value->subcategory->image_name ) }}" width="100px" height="100px">
               
              </td>
              <td width="50%">{{ str_limit($value->subcategory->description , 200 )}} </td>
              <td>
                <a class="status-category btn @if($value->status == 1) btn-success @else btn-primary @endif" href="javascript::void();" onclick="event.preventDefault();
                                     document.getElementById('status-category-{{ $value->subcategory->id }}').submit();">
                                  {{ $value->status == 1 ? 'Active' : 'Inactive'  }} 
                 </a>
                <form id="status-category-{{ $value->subcategory->id }}" action="{{ route('subcategories.status',$value->subcategory->id) }}" method="POST" style="display: none;">
                 @method('post')
                        @csrf
                </form> 
              </td>
    

              <td>
              <a href="{{ route('new.product',[$value->subcategory->id] ) }}" class="btn btn-primary">
                Products
              </a> 

                <a onclick="deleteCat({{$value->id}})" href="javascript:;" class="text-danger"> <i class="fas fa-trash"></i> 
                </a> 
               
              <a href="{{route('subcategories.edit' , $value->subcategory->id)}}" class="text-primary"> <i class="fas fa-edit"></i> </a>

              <form id="delete-subcategory-{{$value->subcategory->id}}" action="{{route('destroy.new.subcategory' , $value->id)}}" method="POST" style="display: none" >
                @csrf 
                @method('DELETE')
              </form>

              </td>
            </tr>
            @endif
            @endforeach
           
          </tbody>
        </table>
      </div>
    </div>
  
  </div>
</div>