routes/web.php
<?php

use UniSharp\LaravelFilemanager\Lfm;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/',  function(){
//     return view('index');
// } )->name('/');

Route::get('admin/migration-command', function () {
    
    \Artisan::call('migrate');
    dd("Done");
});


Route::get('/' , 'Frontend\HomeController@index')->name('/');
// Route::get('/' , 'HomeController@index')->name('/');
Route::get('/home' , 'HomeController@showDashbaord' )->name('home');

Route::get('/admin/login' , 'HomeController@login' )->name('dashboard.login');

Route::group( ['prefix'=>'admin','as'=>'admin.' , 'middleware' => ['auth' , 'admin']  ] , function(){


    Route::get('/',  'HomeController@adminDashboard' )->name('index');
    Route::get('/user/{id}/profile' , 'UserController@editProfile')->name('user.profile');
    Route::post('/user/{id}/profile/update' , 'UserController@updateProfile')->name('user.profile.update');
    Route::resource('users', 'UserController');
    Route::resource('category', 'CategoryController');
    Route::resource('subcategory', 'SubCategoryController');
    Route::resource('product', 'ProductController');
    Route::post('product-on-sale/{id}', 'ProductController@product_on_sale')->name('product.on.sale');
    Route::post('product-status/{id}', 'ProductController@change_status')->name('product.status');
    Route::resource('vendors', 'VendorController');
    Route::resource('brands', 'BrandController');
    Route::post('brands-status/{id}', 'BrandController@change_status')->name('brands.status');
    Route::resource('delivery_boys', 'DeliveryBoyController');
    Route::resource('coupens', 'CoupenController');
    Route::resource('newsletters', 'NewsletterController');
    Route::get('media-managment' , function(){
        return view('media.media'); })->name('media-managment');
    Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['auth']], function () {
        Lfm::routes();
    });
} );


    Route::get('/', 'Frontend\HomeController@mainPage' )->name('index');
    Route::get('/about-us', 'HomeController@about_us' )->name('about-us');


    Route::group( ['prefix'=>'dashboard','as'=>'dashboard.' , 'middleware' => 'auth'  ]  , function(){
        Route::get('/' , 'HomeController@customerDashboard' )->name('index');
} );

Route::get('clear' , function(){
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    return 'clear';
} );

Route::get('test', function () {
    return view('test');
    // return view('testing');

});

Auth::routes();


// Route::get('test' , function(){
//     return view('layouts.admin');
// } );



//  admin routes 
Route::resource('admin/categories','Admin\CategoryController');
Route::post('admin/categories-status/{id}','Admin\CategoryController@change_status')->name('categories.status');
Route::resource('admin/subcategory-type','Admin\SubcategoryTypeController');
Route::post('admin/subcategory-typ-status/{id}','Admin\SubcategoryTypeController@change_status')->name('subcategory.typ.status');
Route::resource('admin/subcategories','Admin\SubcategoryController');
Route::post('admin/subcategories-status/{id}','Admin\SubcategoryController@change_status')->name('subcategories.status');

Route::resource('admin/home-slider','Admin\HomeSliderController');
Route::post('admin/home-slider-status/{id}','Admin\HomeSliderController@change_status')->name('home.slider.status');
Route::resource('admin/banner-images','Admin\BannerImagesController');
Route::post('admin/banner-images-status/{id}','Admin\BannerImagesController@change_status')->name('banner.images.status');

Route::resource('admin/products','Admin\ProdcutController');
Route::post('admin/products-status/{id}','Admin\ProdcutController@change_status')->name('products.status');

Route::resource('admin/featured-products','Admin\FeaturedCategoryController');
// featured-subcategory-type routes 
Route::get('admin/featured-subcateory-type/{id}','Admin\FeaturedCategoryController@features_subcatet')->name('featured.subcategory.type');
Route::get('admin/create-featured-subcateory-type/{id}','Admin\FeaturedCategoryController@create_features_subcatet')->name('create.featured.subcategory.type');
Route::post('admin/store-featured-subcateory-type/{id}','Admin\FeaturedCategoryController@store_features_subcatet')->name('store.featured.subcategory.type');
Route::delete('admin/destroy-featured-subcateory-type/{id}','Admin\FeaturedCategoryController@destroy_features_subcatet')->name('destroy.featured.subcategory.type');

// featured-subcategory routes 
Route::get('admin/featured-subcateory/{id}','Admin\FeaturedCategoryController@features_subcategory')->name('featured.subcategory');
Route::get('admin/create-featured-subcateory/{id}','Admin\FeaturedCategoryController@create_features_subcategory')->name('create.featured.subcategory');
Route::post('admin/store-featured-subcateory/{id}','Admin\FeaturedCategoryController@store_features_subcategory')->name('store.featured.subcategory');
Route::delete('admin/destroy-featured-subcateory/{id}','Admin\FeaturedCategoryController@destroy_features_subcategory')->name('destroy.featured.subcategory');

// featured-products routes 
Route::get('admin/featured-product/{id}','Admin\FeaturedCategoryController@features_products')->name('featured.product');
Route::get('admin/create-featured-products/{id}','Admin\FeaturedCategoryController@create_features_products')->name('create.featured.products');
Route::post('admin/store-featured-products/{id}','Admin\FeaturedCategoryController@store_features_products')->name('store.featured.products');
Route::delete('admin/destroy-featured-products/{id}','Admin\FeaturedCategoryController@destroy_features_products')->name('destroy.featured.products');



// new products routes
Route::resource('admin/new-products','Admin\NewProductController');
// featured-subcategory-type routes 
Route::get('admin/new-subcateory-type/{id}','Admin\NewProductController@features_subcatet')->name('new.subcategory.type');
Route::get('admin/create-new-subcateory-type/{id}','Admin\NewProductController@create_features_subcatet')->name('create.new.subcategory.type');
Route::post('admin/store-new-subcateory-type/{id}','Admin\NewProductController@store_features_subcatet')->name('store.new.subcategory.type');
Route::delete('admin/destroy-new-subcateory-type/{id}','Admin\NewProductController@destroy_features_subcatet')->name('destroy.new.subcategory.type');

// featured-subcategory routes 
Route::get('admin/new-subcateory/{id}','Admin\NewProductController@features_subcategory')->name('new.subcategory');
Route::get('admin/create-new-subcateory/{id}','Admin\NewProductController@create_features_subcategory')->name('create.new.subcategory');
Route::post('admin/store-new-subcateory/{id}','Admin\NewProductController@store_features_subcategory')->name('store.new.subcategory');
Route::delete('admin/destroy-new-subcateory/{id}','Admin\NewProductController@destroy_features_subcategory')->name('destroy.new.subcategory');

// featured-products routes 
Route::get('admin/new-product/{id}','Admin\NewProductController@features_products')->name('new.product');
Route::get('admin/create-new-products/{id}','Admin\NewProductController@create_features_products')->name('create.new.products');
Route::post('admin/store-new-products/{id}','Admin\NewProductController@store_features_products')->name('store.new.products');
Route::delete('admin/destroy-new-products/{id}','Admin\NewProductController@destroy_features_products')->name('destroy.new.products');


// hot products route
Route::resource('admin/hot-products','Admin\HotProductController');
// featured-subcategory-type routes 
Route::get('admin/hot-subcateory-type/{id}','Admin\HotProductController@features_subcatet')->name('hot.subcategory.type');
Route::get('admin/create-hot-subcateory-type/{id}','Admin\HotProductController@create_features_subcatet')->name('create.hot.subcategory.type');
Route::post('admin/store-hot-subcateory-type/{id}','Admin\HotProductController@store_features_subcatet')->name('store.hot.subcategory.type');
Route::delete('admin/destroy-hot-subcateory-type/{id}','Admin\HotProductController@destroy_features_subcatet')->name('destroy.hot.subcategory.type');

// featured-subcategory routes 
Route::get('admin/hot-subcateory/{id}','Admin\HotProductController@features_subcategory')->name('hot.subcategory');
Route::get('admin/create-hot-subcateory/{id}','Admin\HotProductController@create_features_subcategory')->name('create.hot.subcategory');
Route::post('admin/store-hot-subcateory/{id}','Admin\HotProductController@store_features_subcategory')->name('store.hot.subcategory');
Route::delete('admin/destroy-hot-subcateory/{id}','Admin\HotProductController@destroy_features_subcategory')->name('destroy.hot.subcategory');

// featured-products routes 
Route::get('admin/hot-product/{id}','Admin\HotProductController@features_products')->name('hot.product');
Route::get('admin/create-hot-products/{id}','Admin\HotProductController@create_features_products')->name('create.hot.products');
Route::post('admin/store-hot-products/{id}','Admin\HotProductController@store_features_products')->name('store.hot.products');
Route::delete('admin/destroy-hot-products/{id}','Admin\HotProductController@destroy_features_products')->name('destroy.hot.products');



Route::post('ajax/listingtab_/{id}','Frontend\HomeController@featured_products');



Route::get('admin/featured-subcateory/{id}','Admin\FeaturedCategoryController@features_subcategory')->name('featured.subcategory');



// Route::resource('admin/new-products','Admin\NewProductsController');
// Route::resource('admin/hot-products','Admin\HotCategoryController');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';
 	protected $primaryKey = 'id';

    protected $guarded = [];

    public function brand_name(){
    	return $this->belongsTo('App\Models\Brand','brand_id')->select('name');
    }
    public function subcategory_name(){
    	return $this->belongsTo('App\Models\Subcategory','subc_id')->select('title');
    }

    public function subcategory(){
    	return $this->belongsTo('App\Models\Subcategory','subc_id');
    }
}

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
// use App\Models\Subcategory;
// use App\Models\Brand;


class Product extends Model
{
    protected $guarded = [];

    public function categories(){
        return $this->belongsToMany('App\Category');
    }

    public function brand_name(){
    	return $this->belongsTo('App\Models\Brand','brand_id')->select('name');
    }
    public function subcategory_name(){
    	return $this->belongsTo('App\Models\Subcategory','subc_id')->select('title');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\Category;
use Illuminate\Http\Request;
use App\Brand;
use App\Models\Subcategory;


class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::all();
        return view('products.index' , compact('products') );
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $subcategory = Subcategory::all();
        $brands = Brand::all();
        return view('products.create' , compact('categories','brands','subcategory') );
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());

        $request->validate([
            'title' =>'required',
            'slug' => 'required',
            'description' => 'sometimes',
            'price' => 'required',
            'discount' => 'sometimes',
            'featured_image' => 'sometimes',
        ]);


        $product = new Product();
        $product->subc_id = $request->subc_id;
        $product->brand_id = $request->brand_id;
        $product->title = $request->title;
        $product->slug = $request->slug;
        $product->description = $request->description;
        $product->price = $request->price;
        $product->discount = $request->discount;
        $product->product_on_sale = $request->product_on_sale;
        $product->status = $request->status;
        $product->user_id = auth()->user()->id;

        if ($request->file('featured_image')) {
            $file = $request->featured_image;
            $folder = 'products';
            $product->featured_image = saveImages($file, $folder);
        }

        $product->save();
     
        if(isset($request->categories))
        $product->categories()->attach($request->categories);
        else
        $product->categories()->attach([1]);

        if($product){
            return redirect('/admin/product')->with('success' , 'Product added successfully');
        }else{
            return redirect()->back()->with('error' , 'Some problem occoured');
        }
    
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $categories = Category::all();
        $subcategory = Subcategory::all();
        $brands = Brand::all();
        return view('products.edit' , compact('brands','subcategory','categories', 'product') );
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
        // dd($request->all()  , $product);
        
        $request->validate([
            'title' =>'required',
            'slug' => 'required',
            'description' => 'sometimes',
            'price' => 'required',
            'discount' => 'sometimes',
            'featured_image' => 'sometimes',
        ]);
        
        $product->subc_id = $request->subc_id;
        $product->brand_id = $request->brand_id;
        $product->title = $request->title;
        $product->slug = $request->slug;
        $product->description = $request->description;
        $product->price = $request->price;
        $product->discount = $request->discount;
        $product->product_on_sale = $request->product_on_sale;
        $product->status = $request->status;
        $product->user_id = auth()->user()->id;

        if ($request->file('featured_image')) {
            $file = $request->featured_image;
            $folder = 'products';
            $old_file_name = $product->featured_image;
            $product->featured_image = saveImages($file, $folder,$old_file_name);
        }

        $product->save();

        if(isset($request->categories))
        $product->categories()->sync($request->categories);
        else
        $product->categories()->sync([1]);

        if($product->save()){
            return redirect('/admin/product')->with('success' , 'Product updated successfully');
        }else{
            return redirect()->back()->with('error' , 'Some problem occoured');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->categories()->sync([]);
        // $product->delete();
        if($product->delete())
        return redirect()->back()->with('success' , 'Product deleted successfuly');
        else
        return redirect()->back()->with('error' , 'Some problem occoured');

    }

    public function product_on_sale($id){

        $product = Product::find($id);
        $product->product_on_sale = $product->product_on_sale == 1 ? 0 : 1;
        $product->save();
        if($product){
            return redirect()->route('product.index')->with('success' , 'Status updated successfully');
        }else{
            return redirect()->back()->with('error' , 'Some problem occoured');
        }

    }   
    public function change_status($id){
    
        $product = Product::find($id);
        $product->status = $product->status == 1 ? 0 : 1;
        $product->save();
        if($product){
            return redirect()->route('products.index')->with('success' , 'Status updated successfully');
        }else{
            return redirect()->back()->with('error' , 'Some problem occoured');
        }
    }
}

resources/views/products/create.blade.php
@extends('layouts.admin')

@section('styles')
<link rel="stylesheet" href="{{asset('/admin-plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('/admin-plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">

@endsection

@section('content')


<div class="row">

    @if($errors->any() )
    @foreach ($errors->all() as $error)
        <p class="alert alert-danger"> {{$error}} </p>
    @endforeach
    @endif

    @if(session()->has('success'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: '{{session("success")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('error'))
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '{{session("error")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('message'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'info',
            title: '{{session("message")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif

    <form action="{{route('admin.product.store')}}" method="POST" style=" width:100%; display:flex;" enctype="multipart/form-data">
      @csrf
  
    <div class="col-md-8" style="padding:10px; padding-left:30px;" >
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Create Product</h3>
      </div>
      <!-- /.card-header -->
      <div style="padding:30px" >
        

        <div class="form-group">
              <label class="col-form-label">Sub category</label>
              <select class="custom-select" name="subc_id" id="subc_id" value="{{old('subc_id')}}" required="">
              <option value="">Select Subcategory</option>
              @if(isset($subcategory) && !empty($subcategory))
                @foreach($subcategory as $key => $value)
                  <option value="{{ $value->id }}">{{ $value->sc_name }}</option>
                @endforeach
              @endif
            </select>
          </div>
        <div class="form-group">
              <label class="col-form-label">Brands</label>
              <select class="custom-select" name="brand_id" id="brand_id" value="{{old('brand_id')}}" required="">
              <option value="">Select Brand</option>
              @if(isset($brands) && !empty($brands))
                @foreach($brands as $key => $value)
                  <option value="{{ $value->id }}">{{ $value->name }}</option>
                @endforeach
              @endif
            </select>
          </div>

          <div class="form-group">
              <label class="col-form-label">Title</label>
              <input type="text" class="form-control" name="title" placeholder="product title" value="{{old('title')}}" required id="post_title" />
              <p class="small">{{config('app.url')}}/<span id="url"></span></p>
              <input type="hidden" name="slug" id="slug" />
          </div>
          <div class="form-group">
              <label class="col-form-label">On Sale</label>
              <select class="custom-select" name="product_on_sale" id="product_on_sale" value="{{old('product_on_sale')}}" required="">
              <option value="">Select On Sale</option>
              <option value="1">Yes</option>
              <option value="0">No</option>
            </select>
          </div>
          <div class="form-group">
              <label class="col-form-label">Status</label>
              <select class="custom-select" name="status" id="status" value="{{old('status')}}" required="">
              <option value="">Select Status</option>
              <option value="1">Active</option>
              <option value="0">Inactive</option>
            </select>
          </div>
          <div class="form-group">
              <label class="col-form-label">Image</label>
              <input type="file" class="form-control" name="featured_image" placeholder="product featured_imag" value="{{old('featured_imag')}}" required id="post_title" />
          </div>

          <div class="form-group">
            <label class="col-form-label">Description</label>
            <textarea class="form-control" rows="10" name="description" placeholder="product description" >{{old('description')}}</textarea>
        </div>
        
        <button type="submit" class="btn btn-success"> <i class="fas fa-plus"></i> Create </button>
    </div>


    </div>
    
  </div>

<div class="col-md-4" style="padding:10px;padding-right:30px" >
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Product Features</h3>
      </div>
      <!-- /.card-header -->
      <div style="padding:10px" >
        <select class="select2bs4" multiple="multiple" name="categories[]" data-placeholder="Select Categories" style="width: 100%;">
          @foreach($categories as $category)
            <option value="{{$category->id}}"> {{$category->name}} </option>
          @endforeach
        </select> 
      </div>
      <hr>

      <div class="p-2">
      <h2 >Featured Image</h2>
      
      <div class="input-group col s10 text-center "  >
        <span class="input-group-btn">
          <a id="lfm" data-input="thumbnail" data-preview="thumbnail" class="btn btn-primary text-white">
            <i class="fas fa-images"></i> Choose
          </a>
          <button class="btn btn-danger" type="button" onclick="remove_featured()"><i class="fas fa-times"></i> Clear</button>
        </span>
        <input id="thumbnail" class="form-control" type="hidden" name="featured_image" value="" onchange="show_image()" >
      </div>
      <hr>
        <div class="row">
           <div class="col s10 text-center">
            <img src="" id="featured_image" style="margin-bottom: 15px; margin-top: 15px; width: auto; height: auto; max-width: 250px; max-height: 250px;display:none; "  />
          </div>
     </div>

    </div>
    <div class="form-group p-2  ">
      <label class="sr-only" for="inlineFormInputGroupUsername">Username</label>
      <div class="row ">
        <div class="col-md-10 m-2">
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text">$ </div>
        </div>
        <input type="text" class="form-control" id="inlineFormInputGroupUsername" placeholder="Price" name="price" required>
      </div>
    </div>
    <div class="col-md-10 m-2">
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text">%</div>
        </div>
        <input type="text" class="form-control" name="discount" id="inlineFormInputGroupUsername" placeholder="Discount">
      </div>
    </div>
    </div>
    </div>
  </div>

  </div>
</form>
</div>



@endsection

@section('scripts')

<script>

  $('#post_title').on('keyup', function(){
    let pretty_url = slugify($(this).val());
    $('#url').html(slugify(pretty_url));
    $('#slug').val(pretty_url);
  });
  
  </script>

<script src=" {{asset('/admin-plugins/select2/js/select2.full.min.js')}}"></script>
<script>

  $('.select2bs4').select2({
    theme: 'bootstrap4',
  });

</script>

<script>
  var route_prefix = "/filemanager";

 </script>

 <script>
  {!! \File::get(base_path('vendor/unisharp/laravel-filemanager/public/js/stand-alone-button.js')) !!}
</script>
<script>
  $('#lfm').filemanager('image', {prefix: route_prefix});
  // $('#lfm').filemanager('file', {prefix: route_prefix});
</script>

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>
  var editor_config = {
    path_absolute : "",
    selector: "textarea[name=description]",
    plugins: [
      "link image"
    ],
    relative_urls: false,
    height: 129,
    file_browser_callback : function(field_name, url, type, win) {
      var x = window.innerWidth || document.documentElement.clientWidth || document.getElementsByTagName('body')[0].clientWidth;
      var y = window.innerHeight|| document.documentElement.clientHeight|| document.getElementsByTagName('body')[0].clientHeight;

      var cmsURL = editor_config.path_absolute + route_prefix + '?field_name=' + field_name;
      if (type == 'image') {
        cmsURL = cmsURL + "&type=Images";
      } else {
        cmsURL = cmsURL + "&type=Files";
      }

      tinyMCE.activeEditor.windowManager.open({
        file : cmsURL,
        title : 'Filemanager',
        width : x * 0.8,
        height : y * 0.8,
        resizable : "yes",
        close_previous : "no"
      });
    }
  };

  tinymce.init(editor_config);
</script>

<script>
  
  function show_image(){
    var thumb = $('#thumbnail').val();
    document.getElementById("featured_image").src = thumb;
    $('#featured_image').show();
  }

  function remove_featured(){
    //document.getElementById("featured_image").src =  '{{url('/')}}/img/no-image-found.jpg';
    document.getElementById("featured_image").src =  null;
    $('#featured_image').hide();
    $('#thumbnail').val(null);

  }
</script>



@endsection

resources/views/products/index.blade.php
@extends('layouts.admin')

@section('styles')
    <style>
      .wrapped{
      word-wrap: break-word;
      }
    </style>
@endsection
@section('content')


<div class="row">


    @if($errors->any() )
    @foreach ($errors->all() as $error)
        <p class="alert alert-danger"> {{$error}} </p>
    @endforeach
    @endif

    @if(session()->has('success'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: '{{session("success")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('error'))
    <script>
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '{{session("error")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif
    @if(session()->has('message'))
    <script>
        Swal.fire({
            position: 'center',
            icon: 'info',
            title: '{{session("message")}} ',
            showConfirmButton: false,
            timer: 1500
          });
    </script>
    @endif

<div class="col-md-12" style="padding:30px" >
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">Products</h3>
        <a href="{{route('admin.product.create')}}" class="btn btn-success float-right" > <i class="fas fa-plus"></i> Create Product</a>
      </div> 
      <!-- /.card-header -->
      <div class="card-body">
        <table class="table table-bordered table-hover">
          <thead>                  
            <tr>
              <th >#</th>
              <th>Name</th>
              <th> Image </th>
              <th>Description</th>
              <th>Price</th>
              
              <th> Discount </th>
              <th> On Sale </th>
              <th> Status </th>
              <th>Created</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
              @foreach ($products as $k => $product)
                  
            <tr>
              <td>{{$k+1}}.</td>
              <td>{{$product->title}}</td>
              <td>
                <img src="{{ asset('/uploads/products/thumbnails'.'/'.$product->featured_image ) }}" width="100px" height="100px"> 
              </td>
              <td width="50%" style="max-width:195px; word-wrap:break-word;">{{ str_limit(strip_tags($product->description) , 200 )}} </td>
              <td> {{$product->price}} </td>
              
              <td> {{ $product->discount }} </td>
              <td>
                <a class="product-on-sale btn @if($product->status == 1) btn-success @else btn-primary @endif" href="javascript::void();" onclick="event.preventDefault();
                                     document.getElementById('product-on-sale-{{ $product->id }}').submit();">
                                  {{ $product->status == 1 ? 'Yes' : 'No'  }} 
                 </a>
                <form id="product-on-sale-{{ $product->id }}" action="{{ route('admin.product.on.sale',$product->id) }}" method="POST" style="display: none;">
                 @method('post')
                        @csrf
                </form> 
              </td>

              <td>
                <a class="status-products btn @if($product->status == 1) btn-success @else btn-primary @endif" href="javascript::void();" onclick="event.preventDefault();
                                     document.getElementById('status-products-{{ $product->id }}').submit();">
                                  {{ $product->status == 1 ? 'Active' : 'Inactive'  }} 
                 </a>
                <form id="status-products-{{ $product->id }}" action="{{ route('admin.product.status',$product->id) }}" method="POST" style="display: none;">
                 @method('post')
                        @csrf
                </form> 
              </td>
              <td> {{$product->created_at->toDateString() }} </td>
              <td> <a onclick="deleteProduct({{$product->id}})" href="javascript:;" class="text-danger"> <i class="fas fa-trash"></i> </a> 
               
              <a href="{{route('admin.product.edit' , $product->id)}}" class="text-primary"> <i class="fas fa-edit"></i> </a>

              <form id="delete-product-{{$product->id}}" action="{{route('admin.product.destroy' , $product->id)}}" method="POST" style="display: none" >
                @csrf 
                @method('DELETE')
              </form>

              </td>
            </tr>
            @endforeach
           
          </tbody>
        </table>
      </div>
    </div>
  
  </div>
</div>

@endsection

@section('scripts')
  <script>
    function deleteProduct(id){

      Swal.fire({
        title: 'Are you sure?',
        text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
      }).then((result) => {
        if (result.value) {
          document.getElementById('delete-product-'+id).submit();
        }
      });

    }   
  </script>
@endsection